id: I4508BE72
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:53:29+00:00'
last_modified: '2022-06-15T18:03:07.713692+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22377
  title: རྩ་རྒྱུད་རྟོག་བདུན་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6CCC:
      image_group_id: I1KG22396
      title: Volume 1 of rdo rje 'jigs byed kyi rtsa ba'i rgyud rtog pa bdun pa sogs/
      total_pages: 1030
      order: 1
      base_file: 6CCC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
